version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"    # веб-интерфейс и API
      - "9001:9001"    # консоль управления
    environment:
      MINIO_ROOT_USER: "minioadmin"   # логин
      MINIO_ROOT_PASSWORD: "minioadmin" # пароль
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  file-postgres:
    container_name: file-postgres
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
      POSTGRES_DB: file-storage
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge

volumes:
  db:
  minio_data:
