services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  file-storage-postgres:
    container_name: file-storage-postgres
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: file-storage
    ports:
      - "5332:5432"

  file-storage:
    container_name: file-storage
    build:
      context: .
      dockerfile: ./cmd/file-storage/Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - file-storage-postgres
    volumes:
      - ./cmd/file-storage/config.yaml:/configs/config.yaml:ro

volumes:
  minio_data:
